version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_MODE: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    env_file:
      - .env.production
    command: "yarn start"
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env.production
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
