version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_MODE: prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env.local
    command: "yarn dev"
    depends_on:
      - db
      - mailpit

  db:
    image: mysql:8.0
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
